### PR TITLE
typo, probably useful, since the point in this sentence is that it is…

### PR DESCRIPTION
**Pull request by bquast**
… plural

### CODE REVIEW

**Comment by AlexMV12** [comment]
Nice catch! Thank you.

**Comment by bquast** [comment]
You're welcome, great intro. I'm trying to reimplement this in R (as my "native" language, for my own understanding)

**Comment by AlexMV12** [comment]
Thanks! This is a good idea, it may be useful even for other people used to R. Feel free to ask for support and thanks for the pull requests.

**Comment by bquast** [comment]
Thank you, that is much appreciated. I have some questions. I will try to see how far I get with the papers and references, otherwise (in all likelihood) I will let you know!

**Comment by bquast** [comment]
This is my first attempt, numerically equivalent

https://gist.github.com/bquast/47d4e1363158e80bf2dd5376e4625b1c

need to still implement the computational part

**Comment by bquast** [comment]
I've wrapped it all in the package, with the steps in the vignettes. decryption from multiplication works

https://github.com/bquast/homomorphicencryption

**Comment by AlexMV12** [comment]
Great work! I hope you are as amazed as I was when I made this work. :)

**Comment by bquast** [comment]
Tnx, yes! more than a decade ago I wrote an RNN from scratch, and this was similarly awesome

**Comment by bquast** [comment]
ps. yesterday I also managed to get BGV to work (ish) based on the post on inferati.com. Might be cool to also do it in Python, I'll have a try at some point, but first planning to move to the addition and multiplication in BGV, which is a slightly bigger leap than in BFV

**Pull request merged**
